Heading color in Video section
PrudinnikDmitriy/Heading-color pull request #1
Opened 2022-10-17 14:27 UTC by PrudinnikDmitriy

2022-10-18 08:34 UTC, yevheniitsuryk requested changes

2022-10-18 08:34 UTC, yevheniitsuryk commented on src/sections/home-video.liquid
> +    .header-color {
@PrudinnikDmitriy did you check header_color when there are two sections on the page?

2022-10-18 08:34 UTC, yevheniitsuryk commented on src/sections/home-video.liquid
> +  }
@PrudinnikDmitriy formatting, pls fix

2022-10-20 14:38 UTC, PrudinnikDmitriy commented on src/sections/home-video.liquid
> +    .header-color {
@yevheniitsuryk fixed

2022-10-20 14:38 UTC, PrudinnikDmitriy commented on src/sections/home-video.liquid
> +  }
@yevheniitsuryk fixed

2022-10-21 07:04 UTC, yevheniitsuryk requested changes

2022-10-21 07:04 UTC, yevheniitsuryk commented on src/sections/home-video.liquid
> +<style>
@PrudinnikDmitriy if you are using one style in style tags, you may move condition out of style tag on the upper level

2022-10-21 07:10 UTC, AndriiHrohodza approved these changes

2022-10-21 07:41 UTC, PrudinnikDmitriy commented on src/sections/home-video.liquid
> +<style>
@yevheniitsuryk fixed

2022-10-21 07:50 UTC, yevheniitsuryk approved these changes

2022-10-21 09:02 UTC, merged